### ISSUE TITLE
Update README ?

### ISSUE THREAD

**Issue by Dyr0tH** [ania221B/website-starter-react-template#1]
Hey there developer  @ania221B , 
The project looks nice & seems very minimal to setup. 
I think you should add the following topics as well in your README.md so that even if a new developer who's starting in front end will get an idea of how to setup this project.

- Add a "How to setup" Block explaning what you should do to get this project up and running as quick as possible
- A little more information about your project

That's all :)

**Comment by ania221B** [comment]
Hello @Dyr0tH! Thank you very much for your comment. I've updated the README file with some basic info about the template and section explaining how to use it. I've built this template for myself and it hasn't crossed my mind that somebody who stumbled upon it may want to use it. But you're right, it's good to describe it anyway. Thank you again. Have a wonderful day 😁

**Comment by Dyr0tH** [comment]
Wonderful !! 😄
